Added module "solar"
vineetred/flowy pull request #25
Opened 2020-07-09 15:57 UTC by Baldomo

I also added a function (`calculate_gmt`) which adjusts timezone offsets based on a location's longitude. It's fairly accurate event for places like Auckland or even further.

2020-07-09 15:57 UTC, Baldomo commented
Note: this PR is still missing the `minutes_since_midnight` function @vineetred

2020-07-09 16:00 UTC, vineetred commented
> Note: this PR is still missing the `minutes_since_midnight` function @vineetred

Will you be adding it to another PR or the same one?

2020-07-09 16:05 UTC, Baldomo commented
Probably this one. I would also like to know how you think to integrate everything into the existing codebase so I can make the required functions public and whatnot. And if you spot anything that should be different, just let me know

2020-07-09 16:07 UTC, vineetred commented
I'll just wait before merging then. 

Regarding how I am planning on intergrating, I am refactoring the ```flowy/lib.rs``` by creating another ```generate_config``` function that takes, as input, the lat and long to get the minute times of sunset and sunrise of a place. Based on this, we generate the config file.

2020-07-09 18:38 UTC, vineetred commented on flowy/src/solar.rs
> +extern crate chrono;
Correct me if I'm wrong, but this is not required from Rust 2018 onwards.

2020-07-09 18:38 UTC, vineetred requested changes
Just the crate import removal changes

2020-07-09 23:05 UTC, Baldomo commented
Whoops sorry I forgot to change that before the commit. I already fixed that and it will be included in the next one :)

2020-07-11 05:51 UTC, vineetred commented
@Baldomo any updates on this?

2020-07-11 07:44 UTC, Baldomo commented
@vineetred yes, I was planning on finishing up this PR today. As for the `minutes_since_midnight` function, I think I'll refactor the module a bit so that it has a new type called `Timetable` which holds the solar timetable and has it own functions, like `minutes_since_midnight` and whatnot. This way the whole thing would be easier to use and somewhat more Rust-y

2020-07-11 10:03 UTC, Baldomo commented
Changes done! As a sidenote for the `Timetable::minutes_since_midnight` function, it will return the number of minutes passed since the last `SolarTime::Midnight` event, which fluctuates and it's pretty much never 0:00 AM, so keep that in mind :)

2020-07-11 10:21 UTC, vineetred commented
> Changes done! As a sidenote for the `Timetable::minutes_since_midnight` function, it will return the number of minutes passed since the last `SolarTime::Midnight` event, which fluctuates and it's pretty much never 0:00 AM, so keep that in mind :)

@Baldomo, how far away is it from 00:00?

2020-07-11 10:40 UTC, vineetred commented
@Baldomo I am not sure what changed in the function calculation, but the times returned by the function ```get_sunrise_sunset``` are different from very different from the correct times. It was working fine in the gist I sent you earlier.

2020-07-11 10:42 UTC, Baldomo commented
Yes they were calculated in UTC time without offset, I just assumed it needed GMT adjustment so I added a simple timezone calculation

2020-07-11 10:47 UTC, vineetred commented
Are these adjustments working? For example, if you input the coordinates for Milan, the sunrise time is show to be ```03:46AM``` but it is off by 2 hours. Similarly, if I check for Hyderabad, the sunrise time show is ```05:18AM``` when the actual time is 30 mins away. The difference are not uniform. I think something is up with the offset being calculated. Can you check?

2020-07-11 10:54 UTC, Baldomo commented
@vineetred This is rather weird, the tests I have are only off by a few minutes ([sunrise-sunset page](https://sunrise-sunset.org/search?location=milan))

![Milan](https://imgur.com/FkiPIEk.png)

2020-07-11 10:57 UTC, vineetred commented
Try these coordinates - ``` 17.3850, 78.4867```. The expected Sunrise, Sunset is ```5:47AM and 6:55PM```

2020-07-11 11:02 UTC, Baldomo commented
You're right, for Hyderabad times are off by around half an hour but it makes sense because India is in GMT+5.5 so not a regular timezone ([see here](https://upload.wikimedia.org/wikipedia/commons/8/88/World_Time_Zones_Map.png)). I could include half-hour timezones in the calculations actually as it is technically still accurate (there are other mini-timezones in big timezones) and some countries have an official half-hour timezone themselves

2020-07-11 11:04 UTC, vineetred commented
@Baldomo, the old gist was able to account for half-hour timezones. Let's just incorporate that in this PR instead as that worked.

2020-07-11 11:28 UTC, Baldomo commented
You're totally right, I figured I could use chrono to do that but I just couldn't wrap my head around how, turns out it's super simple :) fixing it now

2020-07-11 11:46 UTC, vineetred commented
@Baldomo the problem still persists. I am unable to get the correct sunrise and sunset times. I think the error lies in the way you are generating the solar timetable. 

See if this can be fixed. Otherwise, I'll just push the earlier gist by tonight.

2020-07-11 11:51 UTC, Baldomo commented
This is really weird, I don't think I changed anything in the table generation. Can you give me an example of a table you get? I'll also check the code

2020-07-11 11:55 UTC, vineetred commented
So in the earlier code, the gist I shared, the sunset and sunrise was calculated using this fn 

```
pub fn get_sunrise_sunset(lat : f64, lon : f64) -> (String, String) {
    // Get the UNIX time    
    let unixtime =  chrono::DateTime::timestamp(&chrono::offset::Utc::now());
    // Get the times of major events
    let tt = solar_timetable(unixtime as f64, lat, lon);
    // Index into the HashMap using SolarTime Enum
    let sunrise = unix_to_normal_time(tt.get(&SolarTime::Sunrise).unwrap().round() as i64);
    let sunset = unix_to_normal_time(tt.get(&SolarTime::Sunset).unwrap().round() as i64);
    // Return tuple of sunsrise and sunset times
    (sunrise, sunset)
}
```
and it was called in the main function using just the lat and long. This gave the correct GMT times.

2020-07-11 12:01 UTC, Baldomo commented
Ok I see, could you please give me some output examples? And are you accounting for the offsets in `unix_to_normal_time`? (it returns the right times for me, just translated in my timezone)

2020-07-11 12:06 UTC, vineetred commented
Oh yes it does give me the correct UTC times. But the gist basically output the GMT times automatically, which doesn't happen in this PR version. I am not sure what bit changed from this version to the gist version.

2020-07-11 12:09 UTC, vineetred commented
@Baldomo I figured out the issue! The problem arises when I run it on Rust Playground -- which, by default, was set to GMT +0. Since Chrono gets its offset from the machine's timezone, it was showing me times without this GMT offset.

Basically, your PR code is fine and works great. Merging right away.

2020-07-11 12:10 UTC, merged